---@diagnostic disable: duplicate-doc-field

---@class AnimDirs
---@field id number
---@field dir string | nil
---@field name string | nil
---@field animIndex number

---@class SyncronizedScene
---@field actorsAligned boolean
---@field deltaZ number
---@field actorAnims AnimDirs[]
---@field objectAnims AnimDirs[]
---@field objects string | nil[]
---@field cameraAnim AnimDirs

---@class Vector3
---@field x number
---@field y number
---@field z number

---@class SceneHandler
---@field loadedAnims? table
---@field loadedModels? table
---@field sceneData SyncronizedScene
---@field sceneLocation Vector3
---@field sceneRotation Vector3
---@field actors table
---@field looped boolean
---@field useDelaZ boolean
---@field callback? function
---@field sceneObjects? table
---@field spawedObjects? table
---@field shouldDelete? boolean
---@field sceneId? number
---@field stopped? boolean
---@field prevntStop? boolean
---@field addCamera? boolean
---@field manualSpawn? boolean
---@field cam? number


---@class CSSProperties
---@field alignContent string | nil aligns a flex container's lines within the flex container when there is extra space on the cross-axis
---@field alignItems string | nil aligns items along the cross-axis of a flex container
---@field alignSelf string | nil aligns a flex item along the cross-axis of the flex container
---@field aspectRatio string | nil specifies the aspect ratio of an element's box
---@field backfaceVisibility string | nil determines whether or not the back face of an element is visible when facing the user
---@field backgroundColor string | nil sets the background color of an element
---@field borderBottomColor string | nil sets the color of the bottom border of an element
---@field borderBottomLeftRadius string | nil sets the radius of the bottom-left corner of an element's border
---@field borderBottomRightRadius string | nil sets the radius of the bottom-right corner of an element's border
---@field borderBottomWidth string | nil sets the width of the bottom border of an element
---@field borderColor string | nil sets the color of all four borders of an element
---@field borderLeftColor string | nil sets the color of the left border of an element
---@field borderLeftWidth string | nil sets the width of the left border of an element
---@field borderRadius string | nil sets the radius of all four corners of an element's border
---@field borderRightColor string | nil sets the color of the right border of an element
---@field borderRightWidth string | nil sets the width of the right border of an element
---@field borderStyle string | nil sets the style of all four borders of an element
---@field borderTopColor string | nil sets the color of the top border of an element
---@field borderTopLeftRadius string | nil sets the radius of the top-left corner of an element's border
---@field borderTopRightRadius string | nil sets the radius of the top-right corner of an element's border
---@field borderTopWidth string | nil sets the width of the top border of an element
---@field borderWidth string | nil sets the width of all four borders of an element
---@field bottom string | nil sets the distance between the bottom edge of an element and the bottom edge of its containing element
---@field color string | nil sets the color of an element's text
---@field decomposedMatrix string | nil specifies a 2D or 3D transformation matrix for an element
---@field direction string | nil specifies the direction of an element's text
---@field display string | nil specifies how an element should be displayed
---@field elevation string | nil specifies the elevation of an element
---@field flex string | nil specifies the length of an element's flex item
---@field flexBasis string | nil specifies the initial length of a flex item
---@field flexDirection string | nil specifies the direction of the main axis of a flex container
---@field flexGrow string | nil specifies how much an element should grow relative to the rest of the flex items in the container
---@field flexShrink string | nil specifies how much an element should shrink relative to the rest of the flex items in the container
---@field flexWrap string | nil specifies whether flex items should wrap or not when there is not enough room on one line
---@field fontFamily string | nil specifies the font family of an element's text
---@field fontSize string | nil specifies the font size of an element's text
---@field fontStyle string | nil specifies the font style of an element's text
---@field fontVariant string | nil specifies the font variant of an element's text
---@field fontWeight string | nil specifies the font weight of an element's text
---@field height string | nil sets the height of an element
---@field includeFontPadding string | nil specifies whether an element's font padding should be included in its height
---@field justifyContent string | nil aligns items along the main axis of a flex container
---@field left string | nil sets the distance between the left edge of an element and the left edge of its containing element
---@field letterSpacing string | nil sets the spacing between characters in an element's text
---@field lineHeight string | nil sets the height of a line of text in an element
---@field margin string | nil sets the margin of an element on all four sides
---@field marginBottom string | nil sets the margin of an element on its bottom side
---@field marginHorizontal string | nil sets the margin of an element on its left and right sides
---@field marginLeft string | nil sets the margin of an element on its left side
---@field marginRight string | nil sets the margin of an element on its right side
---@field marginTop string | nil sets the margin of an element on its top side
---@field marginVertical string | nil sets the margin of an element on its top and bottom sides
---@field maxHeight string | nil sets the maximum height of an element
---@field maxWidth string | nil sets the maximum width of an element
---@field minHeight string | nil sets the minimum height of an element
---@field minWidth string | nil sets the minimum width of an element
---@field opacity string | nil sets the opacity of an element
---@field overflow string | nil specifies what should happen when an element's content overflows its container
---@field overlayColor string | nil specifies the color of an element's overlay
---@field padding string | nil sets the padding of an element on all four sides
---@field paddingBottom string | nil sets the padding of an element on its bottom side
---@field paddingHorizontal string | nil sets the padding of an element on its left and right sides
---@field paddingLeft string | nil sets the padding of an element on its left side
---@field paddingRight string | nil sets the padding of an element on its right side
---@field paddingTop string | nil sets the padding of an element on its top side
---@field paddingVertical string | nil sets the padding of an element on its top and bottom sides
---@field position string | nil specifies the position of an element
---@field resizeMode string | nil specifies how an element's content should be resized to fit its container
---@field right string | nil sets the distance between the right edge of an element and the right edge of its containing element
---@field rotation string | nil specifies the rotation of an element
---@field scaleX string | nil specifies the horizontal scaling of an element
---@field scaleY string | nil specifies the vertical scaling of an element
---@field shadowColor string | nil specifies the color of an element's shadow
---@field shadowOffset string | nil specifies the offset of an element's shadow
---@field shadowOpacity string | nil specifies the opacity of an element's shadow
---@field shadowRadius string | nil specifies the radius of an element's shadow
---@field textAlign string | nil specifies the horizontal alignment of an element's text
---@field textAlignVertical string | nil specifies the vertical alignment of an element's text
---@field textDecorationColor string | nil specifies the color of an element's text decoration
---@field textDecorationLine string | nil specifies the type of text decoration to apply to an element's text
---@field textDecorationStyle string | nil specifies the style of an element's text decoration
---@field textShadowColor string | nil specifies the color of an element's text shadow
---@field textShadowOffset string | nil specifies the offset of an element's text shadow
---@field textShadowRadius string | nil specifies the radius of an element's text shadow
---@field tintColor string | nil specifies the tint color of an element
---@field top string | nil sets the distance between the top edge of an element and the top edge of its containing element
---@field transform string | nil specifies a 2D or 3D transformation to apply to an element
---@field transformMatrix string | nil specifies a 2D or 3D transformation matrix to apply to an element
---@field translateX string | nil specifies the horizontal translation of an element
---@field translateY string | nil specifies the vertical translation of an element
---@field width string | nil sets the width of an element
---@field writingDirection string | nil specifies the writing direction of an element's text
---@field zIndex string | nil sets the z-index of an element
---@field text? string For `Button`, `Divider`<p>Text displayed.
---@field onClick? fun(name: string, id: number) Only for: `Button`<p>Function Event, triggered when button is clicked.
---@field dashed? boolean Only for: `Divider`<p>Makes the divider dashed.
---@field orientation? "left" | "right" | "center" For `Divider`<p>Position of the title inside the divider.
---@field orientationMargin? number For `Divider`<p>The margin between the title and the divider's closest border.
---@field plain? boolean For `Divider`<p>Weather text is shown as plain text.
---@field type? string For `Button`:<p>string: `primary`, `default`, `dashed`, `text`, `link`<p>For `Divider`:<p>string: `horizontal`, `vertical`
---@field vertical? boolean For `Flex`:<p>When true the direction of the flex is vertical.<p>For `Slider`:<p>Sets the slider to vertical.
---@field wrap? boolean For `Flex`:<p>Auto wrap in line.
---@field justify? string For `Flex`:<p>`flex-start`, `center`, `flex-end`, `space-between`, `space-around`, `space-evenly`.
---@field align? "flex-start" | "center" | "flex-end" For `Flex`<p>`flex-start`, `center`, `flex-end`.
---@field gap? string | number For `Flex`<p>`small`, `middle`, `large` are presets. `number` is defaulted to pixels.
---@field min? number For `Slider`<p>Sets the minimum number.
---@field max? number For `Slider`<p>Sets the maximum number.
---@field defaultValue? number For `Slider`<p>Sets the default number.
---@field disabled? boolean For `Slider`, `Dropdown`:<p>Weather the slider is disabled.
---@field step? number For `Slider`:<p>Sets the amount for each step in the slider.
---@field autoFocus? boolean For `Slider`, `Dropdown`<p>When `true` the slider will be focused when opened.
---@field keyboard? boolean For `Slider`<p>When `true` the slider can be controlled with the keyboard.
---@field dots? boolean For `Slider`:<p>...
---@field range? boolean For `Slider`:<p>When `true` the slider has 2 dots to move.
---@field reverse? boolean For `Slider`:<p>When `true` the slider is reversed.
---@field direction? "vertical" | "horizontal" For `Space`<p>Sets the directiopn the space has.
---@field size? 'small' | 'middle' | 'large' | number For `Space`<p>The size between spacing of each element.
---@field align? "center" | "start" | "end" | "baseline" For `Space`<p>Where the elements are aligned to.
---@field wrap? boolean For `Space`<p>Auto wrap in line.
---@field compact? boolean For `Space`<p>Compacts the spacing.
---@field items? table For `Dropdown`<p>Displayed items in the dropdown.
---@field placement? "topLeft" | "topCenter" | "topRight" | "bottomLeft" | "bottomCenter" | "bottomRight" | "top" | "bottom" For `Dropdown`<p>Placement of the popup.
---@field trigger? "contextMenu" | "click" | "hover" For `Dropdown`<p>How the dropdown is triggered.
---@field type? "button" For `Dropdown`<p>Type of dropdown.
---@field selectable? boolean For `Dropdown`<p>Enables so user can select items.
---@field multiple? boolean For `Dropdown`<p>Enables so user can select multiple items.
---@field defaultSelectedKeys? string[] For `Dropdown`<p>Keys of dropdown that are selected by default.
---@field triggerSubMenuAction? "click" | "hover" For `Dropdown`<p>How sub-menues are opened.
---@field onClick? fun(id: number, uiName: string, key: string) For `Dropdown`<p>Function Event, triggered when a child element is selected from a dropdown.
---@field onSelect? fun(id: number, uiName: string, key: string, selectedKeys: string[]) For `Dropdown`.
---@field onDeselect? fun(id: number, uiName: string, key: string, selectedKeys: string[]) For `Dropdown`.
---@field onOpenChange? fun(id: number, uiName: string, open: boolean, info: any) For `Dropdown`.
---@field onSubMenuOpenChange? fun(id: number, name: string, openKeys: string[]) For `Dropdown`.
---@field options? table For `AutoComplete`<p>Options/Suggestions.
---@field defaultValue? string For `AutoComplete`<p>Default selected value.
---@field placeholder? string For `AutoComplete`<p>Placeholder string.
---@filed allowClear? boolean For `AutoComplete`<p>Shows a clear button.
---@field autoFocus? boolean For `AutoComplete`<p>Focuses the element when its shown
---@field backfill? boolean For `AutoComplete`<p>Allows user to navigate with keyboard
---@field bordered? boolean For `AutoComplete`<p>Weather it has a border.
---@field defaultOpen? boolean For `AutoComplete`<p>When true the autocomplete popup is shown.
---@field disabled? boolean For `AutoComplete`<p>Weather the autocomplete is disabled
---@field notFoundContent? string For `AutoComplete`<p>String showed when no suggestion macthes the users input.
---@field status? "error" | "warning" For `AutoComplete`<p>Sets the outliune of the autocomplete
---@field onBlur? fun() For `AutoComplete`<p>Fired when the autocomplete is focused.
---@field onChange? fun(id: number, uiName: string, value: string) For `AutoComplete`<p>Fires when user changes input
---@field onDropdownVisibleChange? fun(id: number, uiName: string, open: boolean) For `AutoComplete`<p>Fires when user opens/closes the popup
---@field onFocus? fun() For `AutoComplete`<p>Fires when user clicks/focuses the autocomplete
---@field onSearch? fun(id: number, uiName: string, value: string) For `AutoComplete`<p>Works like onChange()...
---@field onSelect? fun(id: number, uiName: string, value: string, option: table) For `AutoComplete`<p>Fires when user select a suggestion/option from autocomplete
---@field onClear? fun() For `AutoComplete`<p>Fires when user clicks the clear button in autocomplete
---@field text? string For `Checkbox`<p>Text displayed.
---@field autoFocuz? boolean For `Checkbox`<p>Focuses the element when its shown
---@field checked? boolean For `Checkbox`<p>Weather the checkbox is checked
---@field defaultChecked? boolean For `Checkbox`<p>Weather the checkbox is checked by default
---@field disabled? boolean For `Checkbox`<p>Weather the checkbox is disabled
---@field indeterminate? boolean For `Checkbox`<p>"The indeterminate checked state of checkbox"
---@field onChange? fun(id: number, uiName: string, event: table|string[]) For `Checkbox`<p>Fires when user changes the checkbox
---@field isGroup? boolean For `Checkbox`<p>Weather the checkbox is a group !!Not Requires Options!!
---@field options? table `Checkbox`<p>Entries for the checkbox group
---@field defaultValue? string[] For `Checkbox`<p>Default selected values
---@field type? "Input"|"Search"|"TextArea" For `Input`<p>Input type
---@field defaultValue? string For `Input`<p>Default value
---@field addonAfter? string For `Input`<p>String after input
---@field addonBefore? string For `Input`<p>String before input
---@field allowClear? boolean For `Input`<p>Shows a clear button when there is any input
---@field bordered? boolean For `Input`<p>Weather the input has a border
---@field disabled? boolean For `Input`<p>Weather the input is disabled
---@field maxLength? number For `Input`<p>Max allowed length of input
---@field prefix? string|table For `Input`<p>String or icon before input
---@field suffix? string|table For `Input`<p>String or icon after input
---@field showCount? boolean For `Input`<p>Shows the count of characters in the input
---@field status? "error"|"warning" For `Input`<p>Sets the outline of the input
---@field size? "large"|"middle"|"small"|number For `Input`<p>Sets the size of the input. When number, its treated as pixels
---@field onChange? fun(id: number, uiName: string, event: table) For `Input`<p>Fires when user changes the input
---@field onPressEnter? fun(id: number, uiName: string, event: table) For `Input`<p>Fires when user presses enter on the keyboard
---@field autoSize? boolean For `Input`(TextArea Only)<p>Auto resize the textarea
---@field enterButton? table For `Input`(Search Only)<p>Button to show on the right side of the input
---@field loading? boolean For `Input`(Search Only)<p>Replaces the search with a loading icon
---@field onSearch? fun(id: number, uiName: string, value: string, event: table, source: table) For `Input`(Search Only)<p>Fires when user presses the search button
---@field title? string For `Popover`<p>Title of the popover.
---@field content? string[] For `Popover`<p>Content of the popover, each entry is a new line.
---@field trigger?  "hover" | "focus" | "click" For `Popover`<p>How the popover is triggered.
---@field open? boolean For `Popover`<p>Weather the popover is open. Requires you to overwrite how the popover is shown.
---@field defaultOpen? boolean For `Popover`<p>Weather the popover is open by default.
---@field arrow? boolean|table For `Popover`<p>Weather the popover has an arrow. When table, it can be styled.
---@field onClick? fun(id: number, name: string, event: table)
---@field title? string For `Popconfirm`<p>Title of the popconfirm.
---@field cancelTexT? string For `Popconfirm`<p>Text of the cancel button.
---@field okText? string For `Popconfirm`<p>Text of the ok button.
---@field description? string For `Popconfirm`<p>Description of the popconfirm.
---@field disabled? boolean For `Popconfirm`<p>Weather the popconfirm should display.
---@field icon? string For `Popconfirm`<p>Icon of the popconfirm.
---@field cancelButtonProps? table For `Popconfirm`<p>Props/Styling of the cancel button.
---@field okButtonProps? table For `Popconfirm`<p>Props/Styling of the ok button.
---@field okType? string For `Popconfirm`<p>Type of the ok button.
---@field showCancel? boolean For `Popconfirm`<p>Weather the cancel button should be shown.
---@field onCancel? fun(id: number, name: string, event: table) For `Popconfirm`<p>Fires when user presses the cancel button.
---@field onConfirm? fun(id: number, name: string, event: table) For `Popconfirm`<p>Fires when user presses the ok button.
---@field onPopupClick? fun(id: number, name: string, event: table) For `Popconfirm`<p>Fires when user clicks anywhere within the popconfirm.
---@field title? string For `Tooltip`<p>Title of the tooltip.
---@field arrow? boolean|table For `Tooltip`<p>Weather the tooltip has an arrow. When table, it can be styled.
---@field color? string For `Tooltip`<p>Background color of the tooltip.
---@field defaultOpen? boolean For `Tooltip`<p>Weather the tooltip is open by default.
---@field mouseEnterDelay? number For `Tooltip`<p>Delay in seconds before the tooltip is shown.
---@field mouseLeaveDelay? number For `Tooltip`<p>Delay in seconds before the tooltip is hidden.
---@field overlayStyle? table For `Tooltip`<p>CSS Properties for the tooltip card (behind visible element).
---@field overlayInnerStyle? table For `Tooltip`<p>CSS Properties for the visible tooltip card.
---@field placement? string For `Tooltip`<p>Placement of the tooltip.
---@field trigger? "hover" | "focus" | "click" | "contentMenu" For `Tooltip`<p>How the tooltip is triggered.
---@field open? boolean For `Tooltip`<p>Weather the tooltip is open. Requires you to overwrite how the tooltip is shown.
---@field onOpenChange? fun(id: number, name: string, open: boolean) For `Tooltip`<p>Fires when tooltip is opened or closed.
---@field open? boolean For `Modal`<p>Controls weather the modal is open.
---@field title? string For `Modal`<p>Title of the modal.
---@field cancelButtonProps? table For `Modal`<p>Props/Styling of the cancel button.
---@field cancelText? string For `Modal`<p>Text of the cancel button.
---@field centered? boolean For `Modal`<p>Weather the modal is centered to users screen.
---@field closeIcon? string For `Modal`<p>Icon of the close button.
---@field confirmLoading? boolean For `Modal`<p>"Loading visual effect for OK button or not"
---@field keyboard? boolean For `Modal`<p>Weather the user can use the keyboard to interact with the modal.
---@field mask? boolean For `Modal`<p>Weather the modal has a mask.
---@field okButtonProps? table For `Modal`<p>Props/Styling of the ok button.
---@field okText? string For `Modal`<p>Text of the ok button.
---@field okType? string For `Modal`<p>Type of the ok button.
---@field autoFocusButton? nil|"ok"|"cancel" For `Modal`<p>Which button should be focused when modal is opened.
---@field icon? string For `Modal`<p>Icon of the modal. Not shown?.?.?
---@field onOk? fun(id: number, name: string, event: table) For `Modal`<p>Fires when user presses the ok button.
---@field onCancel? fun(id: number, name: string, event: table) For `Modal`<p>Fires when user presses the cancel button.
---@field afterClose? fun(id: number, name: string) For `Modal`<p>Fires when modal is closed.
---@field afterOpenChange? fun(id: number, name: string, open: boolean) For `Modal`<p>Fires when modal is opened or closed.
---@field checked? boolean For `Switch`<p>Weather the switch is checked.
---@field defaultChecked? boolean For `Switch`<p>Weather the switch is checked by default.
---@field disabled? boolean For `Switch`<p>Weather the switch is disabled.
---@field loading? boolean For `Switch`<p>Weather the switch is loading.
---@field size? "default"|"small" For `Switch`<p>Sets the size of the switch.
---@field autoFocus? boolean For `Switch`<p>Focuses the element when its shown
---@field checkedChildren? string|table For `Switch`<p>String or icon shown when switch is checked.
---@field unCheckedChildren? string|table For `Switch`<p>String or icon shown when switch is unchecked.